FROM nvcr.io/nvidia/isaac-lab:2.3.0

RUN touch /isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/torch/_vendor/packaging/_structures.py

RUN apt-get update && apt-get install -y gnupg wget && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-compiler-12-8 cuda-cudart-dev-12-8 && \
    rm -f cuda-keyring_1.1-1_all.deb && \
    apt-get clean

ENV CUDA_HOME=/usr/local/cuda-12.8
ENV TORCH_CUDA_ARCH_LIST="8.0"

RUN git clone https://github.com/NVlabs/curobo.git /tmp/curobo && \
    cd /tmp/curobo && git checkout v0.7.5 && \
    /isaac-sim/python.sh -m pip install -e ".[no_dev]" --no-build-isolation && \
    rm -rf /tmp/curobo
