asset_path: /home/vladi/IsaacLab/master_isaac/throwing_enviroment/meshes/obstacle_box.obj
usd_dir: /home/vladi/IsaacLab/master_isaac/throwing_enviroment/generated_usd
usd_file_name: obstacle_box.usd
force_usd_conversion: false
make_instanceable: false
mass_props:
  mass: 0.15
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: false
  disable_gravity: false
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 1000.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 0
  sleep_threshold: 0.005
  stabilization_threshold: 0.0025
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props: null
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 0.001
- 0.001
- 0.001
##
# Generated by MeshConverter on 2026-06-06 at 17:47:50.
##
